#!/usr/bin/env python3
"""Orchestrator: generate the grower field dashboard and findings report.

Usage:
    python run_all.py [grower_slug]
"""

from __future__ import annotations

import sys
from pathlib import Path

# Add parent dirs to path so we can import from sibling modules
_HERE = Path(__file__).resolve().parent
_SRC = _HERE
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC.parent))  # skill root

from grower_dashboard import generate_grower_dashboard


def generate_findings(grower_slug: str, data_root: str, output_dir: str) -> str:
    """Generate findings.md with written interpretation."""
    from grower_dashboard import GrowerDashboardGenerator

    gen = GrowerDashboardGenerator(grower_slug=grower_slug, data_root=data_root)
    gen._discover_and_load()
    gen._compute_kpis()
    narrative = gen._generate_narrative()
    k = gen.kpis

    out = Path(output_dir) / "findings.md"
    out.parent.mkdir(parents=True, exist_ok=True)

    md = f"""# {gen.display_name} Grower — Field Analysis Findings

## Farm Overview
{gen.display_name} operates {k['total_fields']} fields spanning {k['total_acres']} acres
in Kossuth County, Iowa. Field sizes range from
{min(f.get('area_acres', 0) for f in gen.fields):.0f} to
{max(f.get('area_acres', 0) for f in gen.fields):.0f} acres.

## Vegetation Health (NDVI)
The 5-year mean NDVI across all field-years is {k['avg_ndvi']}.
Crop type explains significant NDVI variation: soybeans typically show
higher and more stable NDVI than corn during the growing season.

## Climate Patterns
Average growing season temperature: {k['avg_temp_c']}°C.
Average GDD (base 10°C): {k['avg_gdd']}.
Average annual rainfall: {k['avg_rainfall_mm']} mm.

## Soil Health
Mean Soil Health Score: {k['avg_shs']}/10.
Key soil averages: OM% = {k['avg_om']}, CEC = {k['avg_cec']} meq/100g,
AWS = {k['avg_aws']} inches, pH = {k['avg_ph']}.

## Sustainability
{k['rotating']} of {k['rotating'] + k['continuous']} fields ({k['rotation_rate']:.0f}%)
are in active crop rotation. Mean Sustainability Index: {k['avg_sust']}/10.

## Key Findings
{narrative.get('section2', '')}

## Recommendations
{narrative.get('section5', '')}

---
_Generated by the my-farm-advisor grower-field-dashboard skill._
"""
    out.write_text(md, encoding="utf-8")
    return str(out.resolve())


def main():
    grower_slug = sys.argv[1] if len(sys.argv) > 1 else "ia-grower"
    data_root = "/home/coder/my-farm-advisor-runtime/data-pipeline"
    output_dir = f"/home/coder/my-farm-advisor-runtime/data-pipeline/growers/{grower_slug}/derived/reports"

    print(f"=== Generating Dashboard for: {grower_slug} ===")

    dashboard_path = generate_grower_dashboard(
        grower_slug=grower_slug,
        data_root=data_root,
    )
    print(f"  Dashboard: {dashboard_path}")

    findings_path = generate_findings(grower_slug, data_root, output_dir)
    print(f"  Findings:   {findings_path}")

    print("\nDone.")


if __name__ == "__main__":
    main()
